Question
    Return from Finally: In Java, does the finally block get executed if we insert a return statement
    inside the try block of a try-catch-finally?

Answer
    - Yes, the finally block will still get executed.
        - the finally block gets executed when the try block exits
        - Even if we try to attempt to exit the try block with ('return', 'continue', 'break', any exceptions)
    - the only way that the finally block is not executed
        - the JVM exits during the try/catch block execution
        - The thread which is executing during the try/catch block gets killed